### ISSUE TITLE
Problem computing glyph bounds of attached marks

### ISSUE THREAD

**Issue by simoncozens** [BlackFoundryCom/black-renderer#132]
I have a glyph ڊ, which is decomposed using mark attachment to `dotbelow-ar=0@221,-25+0|dal-ar=0+3391`. calcGlyphLineBounds calculates its bounding box like so:

https://github.com/BlackFoundryCom/black-renderer/blob/76eed169368f90bca617f29c095644d5316d2428/Lib/blackrenderer/render.py#L110-L121

If we annotate this:

```
Original bounds of dotbelow-ar are (112, -194, 248, -55)
Offset bounds of dotbelow-ar are (333, -219, 469, -80)
Union bounds so far are (333, -219, 469, -80)
Original bounds of dal-ar are (34, 0, 372, 398)
Offset bounds of dal-ar are (34, 0, 372, 398)
Union bounds so far are (34, -219, 469, 398)
```

According to this, the addition of the dotbelow-ar glyph pushes out the maxX of the bounds from 372 to 469.
Except it doesn't: the ink of the dotbelow-ar glyph is entirely contained within the ink of the dal-ar:

![shape](https://user-images.githubusercontent.com/106728/212381228-62035394-e9a2-4cfc-9223-b881b16ea1fd.png)

There is some trick to computing the bounds of a mark-positioned glyph, but unfortunately I can't exactly remember what it is. :-/

(This matters because comparing renderings of a precomposed and a decomposed glyph fails because even though they have the same content, the canvases end up having different widths.)

**Comment by justvanrossum** [comment]
Interesting. However, if I visualize those numbers, I get this:

![bounding_boxes](https://user-images.githubusercontent.com/4246121/212461231-e5f2c7da-b083-494b-9527-7b7196ba81eb.png)

(Red: original bounding box, blue: offset bounding box)

I'm not sure what this means, but it suggests the "original" bounds for `dotbelow-ar` are already offset.

Any way I can play with (a subset of) this font? Privately would be fine, too.

**Comment by justvanrossum** [comment]
I wonder if I misunderstood HB's `get_glyph_extents`:

https://github.com/BlackFoundryCom/black-renderer/blob/76eed169368f90bca617f29c095644d5316d2428/Lib/blackrenderer/font.py#L427-L436

**Comment by simoncozens** [comment]
It's a new version of Noto Naskh Arabic. Attached.
[nnu-reengineer.zip](https://github.com/BlackFoundryCom/black-renderer/files/10416981/nnu-reengineer.zip)

**Comment by justvanrossum** [comment]
Unfortunately I cannot reproduce it. If I add a print to `calcGlyphLineBounds()` like so:

```diff
diff --git a/Lib/blackrenderer/render.py b/Lib/blackrenderer/render.py
index 4455311..d4fc05c 100644
--- a/Lib/blackrenderer/render.py
+++ b/Lib/blackrenderer/render.py
@@ -119,6 +119,7 @@ def calcGlyphLineBounds(glyphLine, font):
             bounds = glyphBounds
         else:
             bounds = unionRect(bounds, glyphBounds)
+        print(f"line bounds after adding {glyph.name}:", bounds)
     return bounds
```

...and then invoke blackrenderer with ccmp=0 and ccmp=1, the respective outputs are:

```
$ blackrenderer NotoNaskhArabic-Regular.ttf ڊ nna_ccmp0.png --features ccmp=0
line bounds after adding dalDotbelow-ar: (34, -197, 372, 398)
$ blackrenderer NotoNaskhArabic-Regular.ttf ڊ nna_ccmp1.png --features ccmp=1
line bounds after adding dotbelow-ar: (139, -197, 275, -58)
line bounds after adding dal-ar: (34, -197, 372, 398)
```
The resulting images have the same dimensions.

**Comment by justvanrossum** [comment]
Any updates on what may have caused your observations?

**Comment by simoncozens** [comment]
I don't know; I think I was doing *something* wrong. We got things working on our end. Sorry to bother!
