### ISSUE TITLE
Translating COLRv1 colorlines to the various backends

### ISSUE THREAD

**Issue by horasio** [BlackFoundryCom/black-renderer#2]
It seems colrv1, cairo, skia, all have different perks about the colorline. I try to list some observations here, mostly in ordere not to forget about them.

1. All API require stops to be in non-decreasing order (that's all good, not an issue).
2. COLRv1 wants at least one stops, Skia want 0 or at least two, Cairo doc is not clear.
3. COLrv1 stops can lie in the interval [-2,2] Cairo and Skia want stops in [0,1].
4. In repeat or mirror mode, COLRv1 repeats or mirrors the **defined band**, which is the subinterval (in [0,1]) from the min stop to the max stop. This can be, for example, [0.2, 0.6]. Whereas Skia requires the defined band to be [0,1]. Speaking to Skia may then require to squeeze the gradient control points (pt1, pt2) to fit the defined band, in non-pad extend mode, when the band is smaller than [0,1].

**Comment by justvanrossum** [comment]
This has been implemented. Should still be verified for radial gradients and checked once we support sweep gradients.
