### ISSUE TITLE
Update to latest spec chages

### ISSUE THREAD

**Issue by drott** [BlackFoundryCom/black-renderer#35]
In particular, there were a couple of changes, the ones I remember and that we did in FreeType, Skia and FontTools:

- `Paint*AroundCenter` for scale, skew and rotate
- Change of precision in a number of values, usually made smaller, in particular in `PaintScale`, for example https://github.com/googlefonts/colr-gradients-spec/commit/f6263236c9c855f6980655301f6039d4fe068989
- No more retrieving of bounding box from `glyf` but either own computation of required glyph allocation size, or using the new `ClipList` and `ClipBox`
- `ColorIndex` was removed in spec, but that might be a no-op in the implementation - inlining of alpha. 
- Affine2x3 matrix is now located at an offset, no longer inline https://github.com/googlefonts/colr-gradients-spec/commit/af58fa7a43dfc40feac6a5cf063db99ffe34122c

CC @anthrotype

**Comment by justvanrossum** [comment]
I can't work on this earlier than september.

**Comment by drott** [comment]
Didn't mean to rush, I just wanted to leave a note of the info I had on the main changes. This helped me to go through them when I was updating FreeType and Skia and thought this info might be useful here.

**Comment by justvanrossum** [comment]
Yes, thanks for the note, that's useful indeed! I didn't mean to make you sound like you're rushing anyone, and just wanted to note that we haven't abandoned the project.
