### ISSUE TITLE
Sweep gradient can only easily be implemented in Skia

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/black-renderer#5]
Skia has [GradientShader.MakeSweep](https://kyamagu.github.io/skia-python/reference/skia.GradientShader.html?highlight=makesweep#skia.GradientShader.MakeSweep) but the other libraries and SVG don't have native support for it, as far as I know.

**Comment by horasio** [comment]
For the other backend/canvases, we can probably do an approximation with a triangle fan (say ≈360 triangles), with a constant color in each triangle. Generate triangle -> clip/cull against clip-extent -> draw.
Would that be useful?
Could also be a linear gradient in each triangle, but i'm not sure it would look good. Worth a try anyway.

**Comment by horasio** [comment]
In fact, mesh patterns seems the way to go, in order to get better approx.

**Comment by justvanrossum** [comment]
Ah great, I see Cairo supports mesh patterns, so that may be a good solution there.

For SVG, a triangle approximation is probably best. SVG to me is more a reference, so I wouldn't be bother much about effiency.

I wonder if for CoreGraphics, [CGShading](https://developer.apple.com/documentation/coregraphics/cgshading?language=objc) could be an option (although I can imagine that being performant in Python, if that API is supported at all by the Python bridge). I have never used that API.

In the worst case we just don't support sweep gradients in some backends.

**Comment by horasio** [comment]
Should that issue be closed?

**Comment by justvanrossum** [comment]
Yes, let's continue in #17.
