### ISSUE TITLE
Re-implement variability

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/black-renderer#53]
This got broken with the recent COLRv1 spec changes

**Comment by justvanrossum** [comment]
Thanks to @anthrotype, this has been implemented in #88.

**Comment by yisibl** [comment]
@justvanrossum Can you release a new version for fontgoggles?

**Comment by justvanrossum** [comment]
Will do! With the caveat that sweep gradients are not working correctly and that variable COLRv1 support only has been lightly tested.

**Comment by justvanrossum** [comment]
https://github.com/justvanrossum/fontgoggles/releases/tag/v1.5.0
