### ISSUE TITLE
SVG metrics — why don't they match font metrics?

### ISSUE THREAD

**Issue by ctrlcctrlv** [BlackFoundryCom/black-renderer#68]
Now, it's possible I'm doing something wrong here, this is using @simoncozens SILE, putting out a bunch of `blackrenderer` output, one after the other, in a nice little row.

![image](https://user-images.githubusercontent.com/838783/151934958-2018c9b5-fe17-4add-8e40-4e649ced688b.png)

# `input.sil`
```tex
\begin{document}
\script[src=packages/inputfilter]
\script[src=packages/svg]
\script[src=blackrenderer]
\set[parameter=shaper.spaceenlargementfactor,value=1]
\set[parameter=shaper.spaceshrinkfactor,value=0]
\set[parameter=shaper.spacestretchfactor,value=0]
\blackrenderer{FRB American Cursive version №2,}

\blackrenderer{via Blackrenderer via SILE}
\end{document}
```

# `blackrenderer.lua`
```lua
local inputfilter = SILE.require("packages/inputfilter").exports
local stringx = require("pl.stringx")
local shellquote = require("pl.utils").escape

local function blackRenderer(text, content)
    local result = {}
    local currentText = ""
    local processSpace
    local len = 0
    
    os.execute("blackrenderer --margin 0 --font-size 12 ../dist/FRBAmericanCursive-400-GuidelinesArrowsRegular.otf ' ' '_space.svg'")

    processSpace = function (_)
        os.execute("blackrenderer --margin 0 --font-size 12 ../dist/FRBAmericanCursive-400-GuidelinesArrowsRegular.otf " .. shellquote(currentText) .. " " .. shellquote(currentText) .. ".svg")
        table.insert(result, inputfilter.createCommand(
            content.pos, content.col, content.line,
            "hbox", {}, table.insert(result, inputfilter.createCommand(content.pos, content.col, content.line,
                "svg", {src = currentText .. ".svg"}, nil
            ))
        ))
        table.insert(result, inputfilter.createCommand(
            content.pos, content.col, content.line,
            "hbox", {}, table.insert(result, inputfilter.createCommand(content.pos, content.col, content.line,
                "svg", {src = "_space.svg"}, nil
            ))
        ))
        len = len + string.len(currentText) + 1
        currentText = ""
    end
  
    local function append(text)
        currentText = currentText .. text
    end

    for i, token in pairs(stringx.split(text, " ")) do
        append(token)
        processSpace()
    end
    return result
end


SILE.registerCommand("blackrenderer", function(_opts, content)
    SILE.process(inputfilter.transformContent(content, blackRenderer))
end, "Blackrenderer SVG in Sile")
```

So I'm not upset that #65 wasn't merged, I wrote it for very selfish reasons, this reason actually. But this is a big problem for me, that SVG metrics aren't font metrics. What to do?

**Comment by justvanrossum** [comment]
What exactly is wrong? What exactly do you mean by "SVG metrics"?

**Comment by ctrlcctrlv** [comment]
I mean that the viewBox does not match the font's metrics. (the viewBox goes before the origin and after the rbearing)

**Comment by ctrlcctrlv** [comment]
Here's a hack that "fixes" it—

![image](https://user-images.githubusercontent.com/838783/151936156-3b166e73-094c-4789-b5ca-555d0c05a664.png)

```diff
diff --git a/blackrenderer2.lua b/blackrenderer.lua
index 6481e29..7a9ea5c 100644
--- a/blackrenderer2.lua
+++ b/blackrenderer.lua
@@ -8,10 +8,12 @@ local function blackRenderer(text, content)
     local processSpace
     local len = 0
     
-    os.execute("blackrenderer --margin 0 --font-size 12 ../dist/FRBAmericanCursive-400-GuidelinesArrowsRegular.otf ' ' '_space.svg'")
-
     processSpace = function (_)
-        os.execute("blackrenderer --margin 0 --font-size 12 ../dist/FRBAmericanCursive-400-GuidelinesArrowsRegular.otf " .. shellquote(currentText) .. " " .. shellquote(currentText) .. ".svg")
+        os.execute("blackrenderer --margin 0 --font-size 12 ../dist/FRBAmericanCursive-400-GuidelinesArrowsRegular.otf " .. shellquote(currentText) .. "' ' " .. shellquote(currentText) .. ".svg")
+        table.insert(result, inputfilter.createCommand(
+            content.pos, content.col, content.line,
+            "glue", {width = "-0.25"}, nil
+        ))
         table.insert(result, inputfilter.createCommand(
             content.pos, content.col, content.line,
             "hbox", {}, table.insert(result, inputfilter.createCommand(content.pos, content.col, content.line,
@@ -20,9 +22,7 @@ local function blackRenderer(text, content)
         ))
         table.insert(result, inputfilter.createCommand(
             content.pos, content.col, content.line,
-            "hbox", {}, table.insert(result, inputfilter.createCommand(content.pos, content.col, content.line,
-                "svg", {src = "_space.svg"}, nil
-            ))
+            "glue", {width = "-1.55"}, nil
         ))
         len = len + string.len(currentText) + 1
         currentText = ""
```

But I'd really rather not need it, I wish I could have correct metrics in my SVG.

**Comment by justvanrossum** [comment]
You can try `--margin 0`, but the output image size is based on the bounding box, not the font metrics.

**Comment by ctrlcctrlv** [comment]
Yes `--margin 0` is in use.

Is there a reason it's based on bbox, or just an implementation decision? Can I PR a font metrics flag?

**Comment by justvanrossum** [comment]
"correct" according to what _you_ need. I want a guarantee that all glyphs are completely visible, for that I need the bounding box.

**Comment by ctrlcctrlv** [comment]
Right, you're right. Correct for what I need, sorry.

**Comment by ctrlcctrlv** [comment]
I've been awake a long time, not trying to offend :)

**Comment by justvanrossum** [comment]
Sure, I'd not be apposed to a flag. So PR would be good (if it works the same way for all output formats + backends).

**Comment by ctrlcctrlv** [comment]
very good , I'll work on that tomorrow :+1: thanks

**Comment by ctrlcctrlv** [comment]
sorry one more question, did you intend for blackrenderer to be used in a TeX-like system like this? I notice it can output to stdout, so actually my version writing all kinds of files is inefficient, I could just use stdin/stdout to SILE's internal SVG rendering function, but I just wanted to see what it would look like before doing more work that might not be useful. I think blackrenderer could plug to LuaLaTeX and XeLaTeX too.

**Comment by justvanrossum** [comment]
Should be possible with only patching `__main__.py` and `render.py`. You may want to use the latest uharfbuzz, which exposes font metrics.

**Comment by justvanrossum** [comment]
The intention for blackrenderer was very simple: to provide a "pure Python" way of rendering COLRv1 fonts, so there's an implementation in addition to Chrome. You're already getting more out of it than it's original scope...

**Comment by ctrlcctrlv** [comment]
I see, I didn't understand why it was written when I found it, I just wanted a very hackable font renderer so I could make it do what I wanted, which you've actually convinced me isn't as "right" as I thought it was :-) but my font still needs it, so in the absence of anything better, I'm using it.

I like it, the code's very good, besides few issues I have which are just coming from my misunderstandings about why it exists. I thought that you wanted to make like, a general purpose font renderer. Well,  we can yet turn it into that, right? :)

**Comment by justvanrossum** [comment]
It does support non-color fonts, too, so it has some overlap with hb-view in terms of functionality.
