### ISSUE TITLE
Skew in x-direction is clockwise, not counter-clockwise

### ISSUE THREAD

**Issue by drott** [BlackFoundryCom/black-renderer#81]
After @justvanrossum's [report on rotation angles](https://bugs.chromium.org/p/skia/issues/detail?id=13190), I was looking closer at Chromium's implementation and comparing. 

It seems that BlackRenderer's skew angle in x-direction works in a clockwise fashion, positive angles turn clockwise, not counter-clockwise. 

In skew along the y-axis, the angle seems to be correct.

If I am not mistaken: For example `glyph_more_samples_skew_25_0_center_0_0_cairo.png` and from the test suite,

![glyph_more_samples_skew_25_0_center_0_0_cairo](https://user-images.githubusercontent.com/1021784/162739213-c449d8f8-e165-4167-8099-6f6e8c06dcdf.png)

and 

`glyph_more_samples_skew_25_0_center_500.0_500.0_cairo.png` 

![glyph_more_samples_skew_25_0_center_500 0_500 0_cairo](https://user-images.githubusercontent.com/1021784/162739472-7ea51313-5114-4cf8-8820-ed72aef40ded.png)

should look more like

![image](https://user-images.githubusercontent.com/1021784/162739418-cc231f6b-7f73-42dc-9a54-86ab5e535dd4.png)

**Comment by justvanrossum** [comment]
You're probably right! I'm looking into it.

**Comment by justvanrossum** [comment]
blackrenderer effectively makes an affine matrix like so:

`[1, math.tan(y), math.tan(x), 1, 0, 0]`

This indeed causes the x angle go clockwise for positive values, in a coordinate system where positive Y values go up.

So this should be

`[1, math.tan(y), -math.tan(x), 1, 0, 0]`

instead, right?

I'm trying to understand the [skia](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/src/ports/SkFontHost_FreeType_common.cpp;l=835) source: I'm I correct that it is working in an upside-down coordinate system, with positive Y values go down? Given that the `center_y` values are negated.

**Comment by drott** [comment]
> I'm trying to understand the [skia](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/src/ports/SkFontHost_FreeType_common.cpp;l=835) source: I'm I correct that it is working in an upside-down coordinate system, with positive Y values go down? Given that the `center_y` values are negated.

The Skia source had a similar bug for the x-coordinate, which I am fixing here. 
https://skia-review.googlesource.com/c/skia/+/529076/1/src/ports/SkFontHost_FreeType_common.cpp

Yes, Skia has a y-down coordinate system. Positive x values go right, positive y values go down.
